# Generated by Django 4.2.6 on 2023-10-22 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('edca946b-93df-4398-bcb8-b9d58733f957'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers_api.typeofteam')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f492987e-25af-466f-a536-0a2bfe04875d'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('characteristics', models.CharField(max_length=255)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers_api.team')),
            ],
        ),
    ]
