# Generated by Django 4.2.6 on 2023-10-23 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workers_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e6b54185-5cc4-49de-b2b1-7506634f7da6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6706f2c0-1422-4254-9e89-b459c0bb5436'), editable=False, primary_key=True, serialize=False),
        ),
    ]
